### ISSUE TITLE
Titanic Spaceship Project

### ISSUE THREAD

**Issue by muhammadanas0716** [muhammadanas0716/Machine-Learning-Projects-101#3]
**What is the awesome project you're thinking of?*
This is a beginner machine learning project, a classification problem to be precise.

**Additional context**
All the problem details can be found here: https://www.kaggle.com/competitions/spaceship-titanic/overview/description

**Comment by parth-verma7** [comment]
Hey @muhammadanas0716  I would like to work on this issue, can this issue be assigned to me under hactober fest?

**Comment by muhammadanas0716** [comment]
Nope, sorry this repo is not part of Hacktoberfest.

**Comment by muhammadanas0716** [comment]
Project Completed!

Link: https://github.com/muhammadanas0716/Machine-Learning-Projects-101/tree/main/Spaceship%20Titanic
