### ISSUE TITLE
Used Car Price prediction Model with deployment on flask.

### ISSUE THREAD

**Issue by Montekkundan** [muhammadanas0716/Machine-Learning-Projects-101#7]
**What is the awesome project you're thinking of?*
Predict the price of an unknown car.

**Additional context**
training data: https://www.kaggle.com/datasets/avikasliwal/used-cars-price-prediction?select=train-data.csv

**Comment by Montekkundan** [comment]
#8 Model added

**Comment by muhammadanas0716** [comment]
Awesome!

**Comment by Montekkundan** [comment]
#10 Project Completed!
